version: "3.3"

networks:
  lnnet:

volumes:
  alice-data:
  bob-data:

services:
  bitcoind:
    container_name: bitcoind
    image: bitcoind:24.0.1
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"

  Alice:
    container_name: Alice
    image: lnd:0.15.5-beta
    networks:
      - lnnet
    expose:
      - "9735"
      - "8080"
      - "10009"
    volumes:
      - alice-data:/lnbits:rw
    environment:
      - tlsextradomain=Alice
      - suportlnbits=1

  lnbits-Alice:
    container_name: lnbits-Alice
    image: lnbits:latest
    networks:
      - lnnet
    ports:
      - 5001:5000
    volumes:
      - alice-data:/lnd:ro
    environment:
      - LND_GRPC_ENDPOINT=Alice

  Bob:
    container_name: Bob
    image: lnd:0.15.5-beta
    networks:
      - lnnet
    expose:
      - "9735"
      - "10009"
    volumes:
      - bob-data:/lnbits:rw
    environment:
      - tlsextradomain=Bob
      - suportlnbits=1

  lnbits-Bob:
    container_name: lnbits-Bob
    image: lnbits:latest
    networks:
      - lnnet
    ports:
      - 5002:5000
    volumes:
      - bob-data:/lnd:ro
    environment:
      - LND_GRPC_ENDPOINT=Bob